name: Automated testing

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  l3build:
    runs-on: ubuntu-latest
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v2
      # GitHub Actions don't regenerate the test if the key doesn't change, so
      # we integrate a random UUID into the key to keep them different.
      # DO NOT CHANGE THIS
      - name: Generate unique ID
        id: get-id
        run: |
          echo -n ::set-output name=id::
          cat /proc/sys/kernel/random/uuid
      # Actually load the cache. Since we never reuse the key, we need restore-keys
      # to indicate the prefix of our caches. This loads the newest cache with this
      # prefix in the key.
      #
      # If we want to force regeneration of the cache, increase the number after
      # *both* instances of "texlive-v"
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: ~/texlive
          key: texlive-v0-${{ steps.get-id.outputs.id }}
          restore-keys: texlive-v0-
      # We need Ghostscript for XeTeX tests.
      - run: sudo apt-get install ghostscript
      - name: Install TeX Live
        uses: zauguin/install-texlive@v1
        with:
          # The following list can be altered to change which TeX Live packages to install.
          packages: |
            # The test framework itself
            l3build
            #
            # Required to build formats
            latex-bin
            tex
            xetex
            #
            # Assuming a 'basic' font set up, metafont is required to avoid
            # warnings with some packages and errors with others
            metafont
            mfware
            # Dependencies for siunitx
            amsmath
            graphics
            l3packages
            tools
            # Dependencies for tests and typesetting
            alphalph
            amsfonts
            atveryend
            babel-catalan
            babel-english
            babel-french
            babel-german
            babel-spanish
            bidi
            booktabs
            cancel
            caption
            carlisle
            cellspace
            cjk
            cjk-ko
            collcell
            colortbl
            csquotes
            datatool
            dvips
            ec
            enumitem
            epstopdf-pkg
            fancyvrb
            fourier
            hologo
            hycolor
            hyperref
            koma-script
            kvoptions
            libertine
            listings
            lualatex-math
            luatexbase
            luatexko
            makeindex
            mathpazo
            mptopdf
            multirow
            natbib
            opensans
            pdftexcmds
            pgfplots
            psnfss
            revtex
            sansmath
            soulpos
            soulutf8
            stringenc
            textcase
            threeparttable
            translations
            underscore
            unicode-math
            was
            xcolor
            xetexko
            xtab
            zref
      - name: Run l3build
        run: l3build ctan -q -H
  
